export interface KeywordDoc {
  name: string;
  category: "function" | "object" | "helping";
  description: string;
  syntax?: string;
  examples?: string[];
  docUrl?: string;
}

function keywordDocUrl(name: string): string {
  return `https://help.malighting.com/grandMA2/en/help/key_keyword_${name.toLowerCase()}.html`;
}

const functionKeywordDocs: KeywordDoc[] = [
  {
    name: "Store",
    category: "function",
    description:
      "Saves programmer content into the show file; by default stores a cue.",
    syntax: 'Store [object-list] "Name" /[option]',
    examples: ['Store Cue 1 "Opening Look"'],
    docUrl: keywordDocUrl("store"),
  },
  {
    name: "Copy",
    category: "function",
    description: "Creates a duplicate of objects.",
    syntax: "Copy [object] At [target]",
    examples: ["Copy Cue 1 At Cue 5"],
    docUrl: keywordDocUrl("copy"),
  },
  {
    name: "Delete",
    category: "function",
    description: "Removes data from the show file.",
    syntax: "Delete [object-list]",
    examples: ["Delete Cue 7"],
    docUrl: keywordDocUrl("delete"),
  },
  {
    name: "Go",
    category: "function",
    description: "Starts the next cue in a sequence (Go+).",
    syntax: "Go [executor]",
    examples: ["Go"],
    docUrl: keywordDocUrl("go"),
  },
  {
    name: "Goto",
    category: "function",
    description: "Jumps directly to a specific cue.",
    syntax: "Goto Cue [number]",
    examples: ["Goto Cue 5"],
    docUrl: keywordDocUrl("goto"),
  },
  {
    name: "Move",
    category: "function",
    description: "Moves objects to a new location.",
    syntax: "Move [object] At [target]",
    examples: ["Move Cue 1 At Cue 10"],
    docUrl: keywordDocUrl("move"),
  },
  {
    name: "Assign",
    category: "function",
    description: "Assigns an object to an executor or button.",
    syntax: "Assign [object] At [executor]",
    examples: ["Assign Sequence 1 At Executor 1"],
    docUrl: keywordDocUrl("assign"),
  },
  {
    name: "Update",
    category: "function",
    description: "Updates stored data with current programmer content.",
    syntax: "Update [object]",
    examples: ["Update Cue 3"],
    docUrl: keywordDocUrl("update"),
  },
  {
    name: "Clear",
    category: "function",
    description: "Clears the programmer or active values.",
    syntax: "Clear",
    examples: ["Clear"],
    docUrl: keywordDocUrl("clear"),
  },
  {
    name: "ClearAll",
    category: "function",
    description: "Clears all programmer content including selection.",
    syntax: "ClearAll",
    examples: ["ClearAll"],
    docUrl: keywordDocUrl("clearall"),
  },
  {
    name: "Select",
    category: "function",
    description: "Selects fixtures or channels for editing.",
    syntax: "Select [object]",
    examples: ["Select Fixture 1 Thru 10"],
    docUrl: keywordDocUrl("select"),
  },
  {
    name: "Off",
    category: "function",
    description: "Turns off an executor or releases a cue.",
    syntax: "Off [executor]",
    examples: ["Off Executor 1"],
    docUrl: keywordDocUrl("off"),
  },
  {
    name: "On",
    category: "function",
    description: "Turns on an executor.",
    syntax: "On [executor]",
    examples: ["On Executor 2"],
    docUrl: keywordDocUrl("on"),
  },
  {
    name: "Edit",
    category: "function",
    description: "Opens an object for editing.",
    syntax: "Edit [object]",
    examples: ["Edit Macro 1"],
    docUrl: keywordDocUrl("edit"),
  },
  {
    name: "Label",
    category: "function",
    description: "Assigns a name or label to an object.",
    syntax: 'Label [object] "name"',
    examples: ['Label Cue 1 "Opening Look"'],
    docUrl: keywordDocUrl("label"),
  },
  {
    name: "Park",
    category: "function",
    description: "Parks fixture output at the current value.",
    syntax: "Park [fixture]",
    examples: ["Park Fixture 3"],
    docUrl: keywordDocUrl("park"),
  },
  {
    name: "Unpark",
    category: "function",
    description: "Releases parked fixtures.",
    syntax: "Unpark [fixture]",
    examples: ["Unpark Fixture 3"],
    docUrl: keywordDocUrl("unpark"),
  },
  {
    name: "Record",
    category: "function",
    description: "Records a macro step.",
    syntax: "Record Macro [number]",
    examples: ["Record Macro 1"],
    docUrl: keywordDocUrl("record"),
  },
  {
    name: "Clone",
    category: "function",
    description: "Clones fixture data from one fixture to another.",
    syntax: "Clone Fixture [source] At Fixture [target]",
    examples: ["Clone Fixture 1 At Fixture 11"],
    docUrl: keywordDocUrl("clone"),
  },
  {
    name: "Import",
    category: "function",
    description: "Imports data from a file.",
    syntax: 'Import [type] "filename"',
    examples: ['Import Library "my_groups"'],
    docUrl: keywordDocUrl("import"),
  },
  {
    name: "Export",
    category: "function",
    description: "Exports data to a file.",
    syntax: 'Export [type] "filename"',
    examples: ['Export Group "my_groups"'],
    docUrl: keywordDocUrl("export"),
  },
  {
    name: "List",
    category: "function",
    description: "Displays a list view of objects.",
    syntax: "List [object-type]",
    examples: ["List Cue"],
    docUrl: keywordDocUrl("list"),
  },
  {
    name: "Load",
    category: "function",
    description: "Loads a cue into the programmer.",
    syntax: "Load Cue [number]",
    examples: ["Load Cue 1"],
    docUrl: keywordDocUrl("load"),
  },
  {
    name: "If",
    category: "function",
    description: "Conditional execution in macros.",
    syntax: "If [condition]",
    examples: ["If $myVar = 1"],
    docUrl: keywordDocUrl("if"),
  },
  {
    name: "Oops",
    category: "function",
    description: "Undoes the last action.",
    syntax: "Oops",
    examples: ["Oops"],
    docUrl: keywordDocUrl("oops"),
  },
  {
    name: "Blind",
    category: "function",
    description: "Enters blind mode for editing without output.",
    syntax: "Blind",
    examples: ["Blind"],
    docUrl: keywordDocUrl("blind"),
  },
  {
    name: "Flash",
    category: "function",
    description: "Momentarily sets an executor to full.",
    syntax: "Flash [executor]",
    examples: ["Flash Executor 1"],
    docUrl: keywordDocUrl("flash"),
  },
  {
    name: "Freeze",
    category: "function",
    description: "Freezes the current output of fixtures.",
    syntax: "Freeze [fixture]",
    examples: ["Freeze Fixture 1"],
    docUrl: keywordDocUrl("freeze"),
  },
  {
    name: "AddUserVar",
    category: "function",
    description: "Adds a new user variable to the show.",
    syntax: 'AddUserVar "$varname" [value]',
    examples: ['AddUserVar "$myVar" 1'],
    docUrl: keywordDocUrl("adduservar"),
  },
  {
    name: "AddVar",
    category: "function",
    description: "Adds a new global variable to the show.",
    syntax: 'AddVar "$varname" [value]',
    examples: ['AddVar "$counter" 0'],
    docUrl: keywordDocUrl("addvar"),
  },
  {
    name: "Align",
    category: "function",
    description: "Aligns attribute values evenly across the current fixture selection.",
    syntax: "Align",
    examples: ["Align"],
    docUrl: keywordDocUrl("align"),
  },
  {
    name: "AlignFaderModules",
    category: "function",
    description: "Aligns fader modules to match the console's executor layout.",
    syntax: "AlignFaderModules",
    examples: ["AlignFaderModules"],
    docUrl: keywordDocUrl("alignfadermodules"),
  },
  {
    name: "All",
    category: "function",
    description: "Selects all fixtures or applies the command to all items.",
    syntax: "All",
    examples: ["All"],
    docUrl: keywordDocUrl("all"),
  },
  {
    name: "AllRows",
    category: "function",
    description: "Selects all rows in the current view or editor.",
    syntax: "AllRows",
    examples: ["AllRows"],
    docUrl: keywordDocUrl("allrows"),
  },
  {
    name: "Backup",
    category: "function",
    description: "Creates a backup of the current show file to an external drive.",
    syntax: "Backup",
    examples: ["Backup"],
    docUrl: keywordDocUrl("backup"),
  },
  {
    name: "Black",
    category: "function",
    description: "Sets the selected fixtures to blackout (dimmer to zero).",
    syntax: "Black",
    examples: ["Black"],
    docUrl: keywordDocUrl("black"),
  },
  {
    name: "BlackScreen",
    category: "function",
    description: "Blacks out the console screen displays.",
    syntax: "BlackScreen",
    examples: ["BlackScreen"],
    docUrl: keywordDocUrl("blackscreen"),
  },
  {
    name: "Blackout",
    category: "function",
    description: "Activates the grandmaster blackout, suppressing all output.",
    syntax: "Blackout",
    examples: ["Blackout"],
    docUrl: keywordDocUrl("blackout"),
  },
  {
    name: "BlindEdit",
    category: "function",
    description: "Enters blind edit mode to modify cue data without affecting live output.",
    syntax: "BlindEdit",
    examples: ["BlindEdit"],
    docUrl: keywordDocUrl("blindedit"),
  },
  {
    name: "Block",
    category: "function",
    description: "Blocks attribute tracking in a cue, preventing values from tracking through.",
    syntax: "Block [object]",
    examples: ["Block Cue 3"],
    docUrl: keywordDocUrl("block"),
  },
  {
    name: "Call",
    category: "function",
    description: "Calls and executes a macro.",
    syntax: "Call Macro [number]",
    examples: ["Call Macro 1"],
    docUrl: keywordDocUrl("call"),
  },
  {
    name: "ChangeDest",
    category: "function",
    description: "Changes the command destination to a different executor or sequence.",
    syntax: "ChangeDest [executor]",
    examples: ["ChangeDest Executor 1.1"],
    docUrl: keywordDocUrl("changedest"),
  },
  {
    name: "ChannelLink",
    category: "function",
    description: "Links or unlinks channels for synchronized control.",
    syntax: "ChannelLink [channel]",
    examples: ["ChannelLink Channel 1"],
    docUrl: keywordDocUrl("channellink"),
  },
  {
    name: "Chat",
    category: "function",
    description: "Opens the chat window for sending messages across the network session.",
    syntax: 'Chat "message"',
    examples: ["Chat \"Check followspot comms\""],
    docUrl: keywordDocUrl("chat"),
  },
  {
    name: "CircularCopy",
    category: "function",
    description: "Creates a circular copy of fixture or cue data.",
    syntax: "CircularCopy [object]",
    examples: ["CircularCopy Cue 1 Thru 5 At Cue 11"],
    docUrl: keywordDocUrl("circularcopy"),
  },
  {
    name: "ClearActive",
    category: "function",
    description: "Clears active (output) values from the programmer, keeping selection.",
    syntax: "ClearActive",
    examples: ["ClearActive"],
    docUrl: keywordDocUrl("clearactive"),
  },
  {
    name: "ClearSelection",
    category: "function",
    description: "Clears the current fixture selection without clearing programmer values.",
    syntax: "ClearSelection",
    examples: ["ClearSelection"],
    docUrl: keywordDocUrl("clearselection"),
  },
  {
    name: "CmdHelp",
    category: "function",
    description: "Displays command-line help and keyword reference information.",
    syntax: "CmdHelp",
    examples: ["CmdHelp"],
    docUrl: keywordDocUrl("cmdhelp"),
  },
  {
    name: "CrashLogCopy",
    category: "function",
    description: "Copies crash log files to a USB drive for analysis.",
    syntax: "CrashLogCopy",
    examples: ["CrashLogCopy"],
    docUrl: keywordDocUrl("crashlogcopy"),
  },
  {
    name: "CrashLogDelete",
    category: "function",
    description: "Deletes crash log files from the console.",
    syntax: "CrashLogDelete",
    examples: ["CrashLogDelete"],
    docUrl: keywordDocUrl("crashlogdelete"),
  },
  {
    name: "CrashLogList",
    category: "function",
    description: "Lists all available crash log files on the console.",
    syntax: "CrashLogList",
    examples: ["CrashLogList"],
    docUrl: keywordDocUrl("crashloglist"),
  },
  {
    name: "Cut",
    category: "function",
    description: "Cuts (removes and copies) objects for pasting elsewhere.",
    syntax: "Cut [object]",
    examples: ["Cut Cue 3"],
    docUrl: keywordDocUrl("cut"),
  },
  {
    name: "DeleteShow",
    category: "function",
    description: "Deletes a show file from the console storage.",
    syntax: 'DeleteShow "showname"',
    examples: ["DeleteShow \"OldTour\""],
    docUrl: keywordDocUrl("deleteshow"),
  },
  {
    name: "DisconnectStation",
    category: "function",
    description: "Disconnects a station from the current network session.",
    syntax: "DisconnectStation [station]",
    examples: ["DisconnectStation 11"],
    docUrl: keywordDocUrl("disconnectstation"),
  },
  {
    name: "DoubleRate",
    category: "function",
    description: "Doubles the current effect rate speed.",
    syntax: "DoubleRate [executor]",
    examples: ["DoubleRate Executor 1.1"],
    docUrl: keywordDocUrl("doublerate"),
  },
  {
    name: "DoubleSpeed",
    category: "function",
    description: "Doubles the executor playback speed.",
    syntax: "DoubleSpeed [executor]",
    examples: ["DoubleSpeed Executor 1.1"],
    docUrl: keywordDocUrl("doublespeed"),
  },
  {
    name: "DropControl",
    category: "function",
    description: "Drops control of shared parameters back to the session.",
    syntax: "DropControl",
    examples: ["DropControl"],
    docUrl: keywordDocUrl("dropcontrol"),
  },
  {
    name: "EndSession",
    category: "function",
    description: "Ends the current network session.",
    syntax: "EndSession",
    examples: ["EndSession"],
    docUrl: keywordDocUrl("endsession"),
  },
  {
    name: "Exit",
    category: "function",
    description: "Exits the current menu, editor, or mode.",
    syntax: "Exit",
    examples: ["Exit"],
    docUrl: keywordDocUrl("exit"),
  },
  {
    name: "Extract",
    category: "function",
    description: "Extracts preset references into hard (absolute) values in cues.",
    syntax: "Extract [object]",
    examples: ["Extract Cue 1"],
    docUrl: keywordDocUrl("extract"),
  },
  {
    name: "Fix",
    category: "function",
    description: "Fixes an executor to keep it visible when changing pages.",
    syntax: "Fix [executor]",
    examples: ["Fix Executor 1"],
    docUrl: keywordDocUrl("fix"),
  },
  {
    name: "FlashGo",
    category: "function",
    description: "Flashes an executor with Go functionality (triggers next cue while held).",
    syntax: "FlashGo [executor]",
    examples: ["FlashGo Executor 2.1"],
    docUrl: keywordDocUrl("flashgo"),
  },
  {
    name: "FlashOn",
    category: "function",
    description: "Flashes an executor with On functionality (turns on while held).",
    syntax: "FlashOn [executor]",
    examples: ["FlashOn Executor 2.1"],
    docUrl: keywordDocUrl("flashon"),
  },
  {
    name: "Flip",
    category: "function",
    description: "Flips between pan/tilt positions on moving head fixtures.",
    syntax: "Flip",
    examples: ["Flip"],
    docUrl: keywordDocUrl("flip"),
  },
  {
    name: "GoBack",
    category: "function",
    description: "Goes back to the previous cue in a sequence (Go minus).",
    syntax: "GoBack [executor]",
    examples: ["GoBack"],
    docUrl: keywordDocUrl("goback"),
  },
  {
    name: "HalfRate",
    category: "function",
    description: "Halves the current effect rate speed.",
    syntax: "HalfRate [executor]",
    examples: ["HalfRate Executor 1.1"],
    docUrl: keywordDocUrl("halfrate"),
  },
  {
    name: "HalfSpeed",
    category: "function",
    description: "Halves the executor playback speed.",
    syntax: "HalfSpeed [executor]",
    examples: ["HalfSpeed Executor 1.1"],
    docUrl: keywordDocUrl("halfspeed"),
  },
  {
    name: "Help",
    category: "function",
    description: "Displays help information for the console or a specific topic.",
    syntax: "Help [topic]",
    examples: ["Help Store"],
    docUrl: keywordDocUrl("help"),
  },
  {
    name: "Highlight",
    category: "function",
    description: "Activates highlight mode to visually identify selected fixtures on stage.",
    syntax: "Highlight",
    examples: ["Highlight"],
    docUrl: keywordDocUrl("highlight"),
  },
  {
    name: "IfActive",
    category: "function",
    description: "Conditional execution based on whether fixtures have active values in the programmer.",
    syntax: "IfActive [fixture]",
    examples: ["IfActive Fixture 1"],
    docUrl: keywordDocUrl("ifactive"),
  },
  {
    name: "IfOutput",
    category: "function",
    description: "Conditional execution based on the current output values of fixtures.",
    syntax: "IfOutput [fixture]",
    examples: ["IfOutput Fixture 1"],
    docUrl: keywordDocUrl("ifoutput"),
  },
  {
    name: "IfProg",
    category: "function",
    description: "Conditional execution based on whether values exist in the programmer.",
    syntax: "IfProg [fixture]",
    examples: ["IfProg Fixture 1"],
    docUrl: keywordDocUrl("ifprog"),
  },
  {
    name: "Info",
    category: "function",
    description: "Displays detailed information about a specified object.",
    syntax: "Info [object]",
    examples: ["Info Fixture 1"],
    docUrl: keywordDocUrl("info"),
  },
  {
    name: "Insert",
    category: "function",
    description: "Inserts a new object at a specified position.",
    syntax: "Insert [object] At [position]",
    examples: ["Insert Cue 2.5"],
    docUrl: keywordDocUrl("insert"),
  },
  {
    name: "Invert",
    category: "function",
    description: "Inverts the current fixture selection or attribute values.",
    syntax: "Invert",
    examples: ["Invert"],
    docUrl: keywordDocUrl("invert"),
  },
  {
    name: "InviteStation",
    category: "function",
    description: "Invites a station to join the current network session.",
    syntax: "InviteStation [station]",
    examples: ["InviteStation 12"],
    docUrl: keywordDocUrl("invitestation"),
  },
  {
    name: "JoinSession",
    category: "function",
    description: "Joins an existing network session on the MA system.",
    syntax: 'JoinSession "sessionname"',
    examples: ["JoinSession \"MainSession\""],
    docUrl: keywordDocUrl("joinsession"),
  },
  {
    name: "Kill",
    category: "function",
    description: "Immediately stops an executor without fade times.",
    syntax: "Kill [executor]",
    examples: ["Kill Executor 1"],
    docUrl: keywordDocUrl("kill"),
  },
  {
    name: "Layer",
    category: "function",
    description: "Selects a layer for editing in effects, presets, or sequences.",
    syntax: "Layer [number]",
    examples: ["Layer 2"],
    docUrl: keywordDocUrl("layer"),
  },
  {
    name: "Learn",
    category: "function",
    description: "Learns speed from manual tap tempo input.",
    syntax: "Learn [executor]",
    examples: ["Learn Executor 1.1"],
    docUrl: keywordDocUrl("learn"),
  },
  {
    name: "LeaveSession",
    category: "function",
    description: "Leaves the current network session.",
    syntax: "LeaveSession",
    examples: ["LeaveSession"],
    docUrl: keywordDocUrl("leavesession"),
  },
  {
    name: "ListEffectLibrary",
    category: "function",
    description: "Lists the contents of the effect library.",
    syntax: "ListEffectLibrary",
    examples: ["ListEffectLibrary"],
    docUrl: keywordDocUrl("listeffectlibrary"),
  },
  {
    name: "ListFaderModules",
    category: "function",
    description: "Lists all connected fader modules and their status.",
    syntax: "ListFaderModules",
    examples: ["ListFaderModules"],
    docUrl: keywordDocUrl("listfadermodules"),
  },
  {
    name: "ListLibrary",
    category: "function",
    description: "Lists the contents of the data library.",
    syntax: "ListLibrary",
    examples: ["ListLibrary"],
    docUrl: keywordDocUrl("listlibrary"),
  },
  {
    name: "ListMacroLibrary",
    category: "function",
    description: "Lists the contents of the macro library.",
    syntax: "ListMacroLibrary",
    examples: ["ListMacroLibrary"],
    docUrl: keywordDocUrl("listmacrolibrary"),
  },
  {
    name: "ListOops",
    category: "function",
    description: "Lists available undo (oops) operations.",
    syntax: "ListOops",
    examples: ["ListOops"],
    docUrl: keywordDocUrl("listoops"),
  },
  {
    name: "ListOwner",
    category: "function",
    description: "Lists owners of shared objects in the session.",
    syntax: "ListOwner",
    examples: ["ListOwner"],
    docUrl: keywordDocUrl("listowner"),
  },
  {
    name: "ListPluginLibrary",
    category: "function",
    description: "Lists the contents of the plugin library.",
    syntax: "ListPluginLibrary",
    examples: ["ListPluginLibrary"],
    docUrl: keywordDocUrl("listpluginlibrary"),
  },
  {
    name: "ListShows",
    category: "function",
    description: "Lists all available show files on the console storage.",
    syntax: "ListShows",
    examples: ["ListShows"],
    docUrl: keywordDocUrl("listshows"),
  },
  {
    name: "ListUpdate",
    category: "function",
    description: "Lists pending software or firmware updates.",
    syntax: "ListUpdate",
    examples: ["ListUpdate"],
    docUrl: keywordDocUrl("listupdate"),
  },
  {
    name: "ListUserVar",
    category: "function",
    description: "Lists all user variables and their current values.",
    syntax: "ListUserVar",
    examples: ["ListUserVar"],
    docUrl: keywordDocUrl("listuservar"),
  },
  {
    name: "ListVar",
    category: "function",
    description: "Lists all global variables and their current values.",
    syntax: "ListVar",
    examples: ["ListVar"],
    docUrl: keywordDocUrl("listvar"),
  },
  {
    name: "LoadNext",
    category: "function",
    description: "Loads the next cue or item in the sequence.",
    syntax: "LoadNext [executor]",
    examples: ["LoadNext Executor 1.1"],
    docUrl: keywordDocUrl("loadnext"),
  },
  {
    name: "LoadPrev",
    category: "function",
    description: "Loads the previous cue or item in the sequence.",
    syntax: "LoadPrev [executor]",
    examples: ["LoadPrev Executor 1.1"],
    docUrl: keywordDocUrl("loadprev"),
  },
  {
    name: "LoadShow",
    category: "function",
    description: "Loads a show file from the console storage.",
    syntax: 'LoadShow "showname"',
    examples: ["LoadShow \"Festival2026\""],
    docUrl: keywordDocUrl("loadshow"),
  },
  {
    name: "Locate",
    category: "function",
    description: "Sets selected fixtures to their default (locate) position for identification.",
    syntax: "Locate",
    examples: ["Locate"],
    docUrl: keywordDocUrl("locate"),
  },
  {
    name: "Lock",
    category: "function",
    description: "Locks the console to prevent unauthorized access.",
    syntax: "Lock",
    examples: ["Lock"],
    docUrl: keywordDocUrl("lock"),
  },
  {
    name: "Login",
    category: "function",
    description: "Logs in a user to the console.",
    syntax: 'Login "username" "password"',
    examples: ["Login \"Admin\" \"admin\""],
    docUrl: keywordDocUrl("login"),
  },
  {
    name: "Logout",
    category: "function",
    description: "Logs out the current user from the console.",
    syntax: "Logout",
    examples: ["Logout"],
    docUrl: keywordDocUrl("logout"),
  },
  {
    name: "MAtricksBlocks",
    category: "function",
    description: "Sets the block size in MAtricks for grouping fixtures.",
    syntax: "MAtricksBlocks [number]",
    examples: ["MAtricksBlocks 2"],
    docUrl: keywordDocUrl("matricksblocks"),
  },
  {
    name: "MAtricksFilter",
    category: "function",
    description: "Sets the filter value in MAtricks for fixture selection patterns.",
    syntax: "MAtricksFilter [number]",
    examples: ["MAtricksFilter 1"],
    docUrl: keywordDocUrl("matricksfilter"),
  },
  {
    name: "MAtricksGroups",
    category: "function",
    description: "Sets the group count in MAtricks for dividing the selection.",
    syntax: "MAtricksGroups [number]",
    examples: ["MAtricksGroups 3"],
    docUrl: keywordDocUrl("matricksgroups"),
  },
  {
    name: "MAtricksInterleave",
    category: "function",
    description: "Sets the interleave value in MAtricks for alternating fixture patterns.",
    syntax: "MAtricksInterleave [number]",
    examples: ["MAtricksInterleave 2"],
    docUrl: keywordDocUrl("matricksinterleave"),
  },
  {
    name: "MAtricksReset",
    category: "function",
    description: "Resets all MAtricks settings to their default values.",
    syntax: "MAtricksReset",
    examples: ["MAtricksReset"],
    docUrl: keywordDocUrl("matricksreset"),
  },
  {
    name: "MAtricksWings",
    category: "function",
    description: "Sets the wings count in MAtricks for mirrored fixture patterns.",
    syntax: "MAtricksWings [number]",
    examples: ["MAtricksWings 2"],
    docUrl: keywordDocUrl("matrickswings"),
  },
  {
    name: "ManualXFade",
    category: "function",
    description: "Activates manual crossfade mode for an executor.",
    syntax: "ManualXFade [executor]",
    examples: ["ManualXFade Executor 1.1"],
    docUrl: keywordDocUrl("manualxfade"),
  },
  {
    name: "MasterFade",
    category: "function",
    description: "Controls the master fade time for executor transitions.",
    syntax: "MasterFade [time]",
    examples: ["MasterFade 3"],
    docUrl: keywordDocUrl("masterfade"),
  },
  {
    name: "Menu",
    category: "function",
    description: "Opens a specified menu on the console display.",
    syntax: "Menu [menuname]",
    examples: ["Menu Setup"],
    docUrl: keywordDocUrl("menu"),
  },
  {
    name: "MidiControl",
    category: "function",
    description: "Sends or configures MIDI control change messages.",
    syntax: "MidiControl [channel] [controller] [value]",
    examples: ["MidiControl 1 7 127"],
    docUrl: keywordDocUrl("midicontrol"),
  },
  {
    name: "MidiNote",
    category: "function",
    description: "Sends or configures MIDI note messages.",
    syntax: "MidiNote [channel] [note] [velocity]",
    examples: ["MidiNote 1 60 100"],
    docUrl: keywordDocUrl("midinote"),
  },
  {
    name: "MidiProgram",
    category: "function",
    description: "Sends or configures MIDI program change messages.",
    syntax: "MidiProgram [channel] [program]",
    examples: ["MidiProgram 1 10"],
    docUrl: keywordDocUrl("midiprogram"),
  },
  {
    name: "Move3D",
    category: "function",
    description: "Moves a 3D object in the virtual stage view.",
    syntax: "Move3D [object]",
    examples: ["Move3D Item3D 1"],
    docUrl: keywordDocUrl("move3d"),
  },
  {
    name: "NetworkInfo",
    category: "function",
    description: "Displays information about the current network configuration.",
    syntax: "NetworkInfo",
    examples: ["NetworkInfo"],
    docUrl: keywordDocUrl("networkinfo"),
  },
  {
    name: "NetworkNodeInfo",
    category: "function",
    description: "Displays detailed information about a specific network node.",
    syntax: "NetworkNodeInfo [node]",
    examples: ["NetworkNodeInfo 1"],
    docUrl: keywordDocUrl("networknodeinfo"),
  },
  {
    name: "NetworkNodeUpdate",
    category: "function",
    description: "Updates the firmware on a network node.",
    syntax: "NetworkNodeUpdate [node]",
    examples: ["NetworkNodeUpdate 1"],
    docUrl: keywordDocUrl("networknodeupdate"),
  },
  {
    name: "NetworkSpeedTest",
    category: "function",
    description: "Runs a network speed test between console and network nodes.",
    syntax: "NetworkSpeedTest",
    examples: ["NetworkSpeedTest"],
    docUrl: keywordDocUrl("networkspeedtest"),
  },
  {
    name: "NewShow",
    category: "function",
    description: "Creates a new empty show file.",
    syntax: 'NewShow "showname"',
    examples: ["NewShow \"PreVis\""],
    docUrl: keywordDocUrl("newshow"),
  },
  {
    name: "NextRow",
    category: "function",
    description: "Moves the selection to the next row in the current view.",
    syntax: "NextRow",
    examples: ["NextRow"],
    docUrl: keywordDocUrl("nextrow"),
  },
  {
    name: "PSR",
    category: "function",
    description: "Performs a Partial Show Read, merging data from another show file.",
    syntax: 'PSR "showname"',
    examples: ["PSR \"TourMaster\""],
    docUrl: keywordDocUrl("psr"),
  },
  {
    name: "PSRList",
    category: "function",
    description: "Lists available data for Partial Show Read operations.",
    syntax: "PSRList",
    examples: ["PSRList"],
    docUrl: keywordDocUrl("psrlist"),
  },
  {
    name: "PSRPrepare",
    category: "function",
    description: "Prepares data for a Partial Show Read operation.",
    syntax: 'PSRPrepare "showname"',
    examples: ["PSRPrepare \"TourMaster\""],
    docUrl: keywordDocUrl("psrprepare"),
  },
  {
    name: "Paste",
    category: "function",
    description: "Pastes previously cut or copied data to a new location.",
    syntax: "Paste [target]",
    examples: ["Paste Cue 5"],
    docUrl: keywordDocUrl("paste"),
  },
  {
    name: "Pause",
    category: "function",
    description: "Pauses a running executor or sequence playback.",
    syntax: "Pause [executor]",
    examples: ["Pause Executor 1"],
    docUrl: keywordDocUrl("pause"),
  },
  {
    name: "PrevRow",
    category: "function",
    description: "Moves the selection to the previous row in the current view.",
    syntax: "PrevRow",
    examples: ["PrevRow"],
    docUrl: keywordDocUrl("prevrow"),
  },
  {
    name: "Preview",
    category: "function",
    description: "Activates preview mode to visualize changes without affecting live output.",
    syntax: "Preview [executor]",
    examples: ["Preview Executor 1.1"],
    docUrl: keywordDocUrl("preview"),
  },
  {
    name: "PreviewEdit",
    category: "function",
    description: "Enters preview edit mode for editing in a preview visualizer.",
    syntax: "PreviewEdit",
    examples: ["PreviewEdit"],
    docUrl: keywordDocUrl("previewedit"),
  },
  {
    name: "Rate1",
    category: "function",
    description: "Resets the executor or effect rate to 1:1 (100%).",
    syntax: "Rate1 [executor]",
    examples: ["Rate1 Executor 1.1"],
    docUrl: keywordDocUrl("rate1"),
  },
  {
    name: "Reboot",
    category: "function",
    description: "Reboots the console hardware.",
    syntax: "Reboot",
    examples: ["Reboot"],
    docUrl: keywordDocUrl("reboot"),
  },
  {
    name: "Release",
    category: "function",
    description: "Releases an executor or attribute values from playback.",
    syntax: "Release [executor]",
    examples: ["Release Executor 1"],
    docUrl: keywordDocUrl("release"),
  },
  {
    name: "ReloadPlugins",
    category: "function",
    description: "Reloads all installed plugins on the console.",
    syntax: "ReloadPlugins",
    examples: ["ReloadPlugins"],
    docUrl: keywordDocUrl("reloadplugins"),
  },
  {
    name: "RemoteCommand",
    category: "function",
    description: "Sends a command to a remote console in the network session.",
    syntax: 'RemoteCommand [station] "command"',
    examples: ["RemoteCommand 11 \"Go Executor 1.1\""],
    docUrl: keywordDocUrl("remotecommand"),
  },
  {
    name: "Remove",
    category: "function",
    description: "Removes fixtures or values from the programmer.",
    syntax: "Remove [fixture]",
    examples: ["Remove Fixture 5"],
    docUrl: keywordDocUrl("remove"),
  },
  {
    name: "RemoveIndividuals",
    category: "function",
    description: "Removes individual fixture values, keeping only range-based values.",
    syntax: "RemoveIndividuals",
    examples: ["RemoveIndividuals"],
    docUrl: keywordDocUrl("removeindividuals"),
  },
  {
    name: "Replace",
    category: "function",
    description: "Replaces one fixture's data with another fixture in the show.",
    syntax: "Replace Fixture [source] At Fixture [target]",
    examples: ["Replace Fixture 101 At Fixture 201"],
    docUrl: keywordDocUrl("replace"),
  },
  {
    name: "ResetDmxSelection",
    category: "function",
    description: "Resets the current DMX selection to default.",
    syntax: "ResetDmxSelection",
    examples: ["ResetDmxSelection"],
    docUrl: keywordDocUrl("resetdmxselection"),
  },
  {
    name: "ResetGuid",
    category: "function",
    description: "Resets the GUID (globally unique identifier) of the console.",
    syntax: "ResetGuid",
    examples: ["ResetGuid"],
    docUrl: keywordDocUrl("resetguid"),
  },
  {
    name: "Restart",
    category: "function",
    description: "Restarts the console application software.",
    syntax: "Restart",
    examples: ["Restart"],
    docUrl: keywordDocUrl("restart"),
  },
  {
    name: "Rotate3D",
    category: "function",
    description: "Rotates a 3D object in the virtual stage view.",
    syntax: "Rotate3D [object]",
    examples: ["Rotate3D Item3D 1"],
    docUrl: keywordDocUrl("rotate3d"),
  },
  {
    name: "SaveShow",
    category: "function",
    description: "Saves the current show file to the console storage.",
    syntax: 'SaveShow "showname"',
    examples: ["SaveShow \"Festival2026\""],
    docUrl: keywordDocUrl("saveshow"),
  },
  {
    name: "Search",
    category: "function",
    description: "Searches for objects or text within the current show.",
    syntax: 'Search "text"',
    examples: ["Search \"Lead Vocal\""],
    docUrl: keywordDocUrl("search"),
  },
  {
    name: "SelFix",
    category: "function",
    description: "Selects fixtures by their fixture ID number.",
    syntax: "SelFix [fixture-id]",
    examples: ["SelFix 1 Thru 10"],
    docUrl: keywordDocUrl("selfix"),
  },
  {
    name: "SelectDrive",
    category: "function",
    description: "Selects a storage drive for file operations.",
    syntax: "SelectDrive [drive]",
    examples: ["SelectDrive USB"],
    docUrl: keywordDocUrl("selectdrive"),
  },
  {
    name: "SetIP",
    category: "function",
    description: "Sets the IP address of the console network interface.",
    syntax: 'SetIP "ip-address"',
    examples: ["SetIP \"192.168.0.100\""],
    docUrl: keywordDocUrl("setip"),
  },
  {
    name: "SetUserVar",
    category: "function",
    description: "Sets the value of an existing user variable.",
    syntax: 'SetUserVar "$varname" [value]',
    examples: ['SetUserVar "$myVar" 42'],
    docUrl: keywordDocUrl("setuservar"),
  },
  {
    name: "SetVar",
    category: "function",
    description: "Sets the value of an existing global variable.",
    syntax: 'SetVar "$varname" [value]',
    examples: ['SetVar "$counter" 10'],
    docUrl: keywordDocUrl("setvar"),
  },
  {
    name: "Setup",
    category: "function",
    description: "Opens the console setup menu.",
    syntax: "Setup",
    examples: ["Setup"],
    docUrl: keywordDocUrl("setup"),
  },
  {
    name: "ShuffleSelection",
    category: "function",
    description: "Shuffles the order of the currently selected fixtures.",
    syntax: "ShuffleSelection",
    examples: ["ShuffleSelection"],
    docUrl: keywordDocUrl("shuffleselection"),
  },
  {
    name: "ShuffleValues",
    category: "function",
    description: "Shuffles attribute values randomly across the selected fixtures.",
    syntax: "ShuffleValues",
    examples: ["ShuffleValues"],
    docUrl: keywordDocUrl("shufflevalues"),
  },
  {
    name: "Shutdown",
    category: "function",
    description: "Shuts down the console safely.",
    syntax: "Shutdown",
    examples: ["Shutdown"],
    docUrl: keywordDocUrl("shutdown"),
  },
  {
    name: "Solo",
    category: "function",
    description: "Activates solo mode, isolating the selected fixtures' output.",
    syntax: "Solo",
    examples: ["Solo"],
    docUrl: keywordDocUrl("solo"),
  },
  {
    name: "Speed",
    category: "function",
    description: "Sets the executor or effect playback speed.",
    syntax: "Speed [executor] [value]",
    examples: ["Speed Executor 1.1 1.25"],
    docUrl: keywordDocUrl("speed"),
  },
  {
    name: "StepFade",
    category: "function",
    description: "Sets the step fade time for cue transitions.",
    syntax: "StepFade [time]",
    examples: ["StepFade 2"],
    docUrl: keywordDocUrl("stepfade"),
  },
  {
    name: "StepInFade",
    category: "function",
    description: "Sets the fade-in time for individual cue steps.",
    syntax: "StepInFade [time]",
    examples: ["StepInFade 1"],
    docUrl: keywordDocUrl("stepinfade"),
  },
  {
    name: "StepOutFade",
    category: "function",
    description: "Sets the fade-out time for individual cue steps.",
    syntax: "StepOutFade [time]",
    examples: ["StepOutFade 1.5"],
    docUrl: keywordDocUrl("stepoutfade"),
  },
  {
    name: "Stomp",
    category: "function",
    description: "Stomps (overrides) all active playbacks for the selected fixtures.",
    syntax: "Stomp",
    examples: ["Stomp"],
    docUrl: keywordDocUrl("stomp"),
  },
  {
    name: "StoreLook",
    category: "function",
    description: "Stores the current live output as a look for later recall.",
    syntax: "StoreLook [number]",
    examples: ["StoreLook 1"],
    docUrl: keywordDocUrl("storelook"),
  },
  {
    name: "Swop",
    category: "function",
    description: "Momentarily activates an executor while turning off all others.",
    syntax: "Swop [executor]",
    examples: ["Swop Executor 1"],
    docUrl: keywordDocUrl("swop"),
  },
  {
    name: "SwopGo",
    category: "function",
    description: "Swop with Go functionality — activates with cue advance while suppressing others.",
    syntax: "SwopGo [executor]",
    examples: ["SwopGo Executor 3.1"],
    docUrl: keywordDocUrl("swopgo"),
  },
  {
    name: "SwopOn",
    category: "function",
    description: "Swop with On functionality — turns on executor while suppressing others.",
    syntax: "SwopOn [executor]",
    examples: ["SwopOn Executor 3.1"],
    docUrl: keywordDocUrl("swopon"),
  },
  {
    name: "SyncEffects",
    category: "function",
    description: "Synchronizes all running effects to a common phase.",
    syntax: "SyncEffects",
    examples: ["SyncEffects"],
    docUrl: keywordDocUrl("synceffects"),
  },
  {
    name: "TakeControl",
    category: "function",
    description: "Takes control of shared parameters in a multi-user session.",
    syntax: "TakeControl",
    examples: ["TakeControl"],
    docUrl: keywordDocUrl("takecontrol"),
  },
  {
    name: "Temp",
    category: "function",
    description: "Temporarily activates an executor while the key or button is held.",
    syntax: "Temp [executor]",
    examples: ["Temp Executor 1"],
    docUrl: keywordDocUrl("temp"),
  },
  {
    name: "TempFader",
    category: "function",
    description: "Assigns a temporary fader function to an executor.",
    syntax: "TempFader [executor]",
    examples: ["TempFader Executor 4.1"],
    docUrl: keywordDocUrl("tempfader"),
  },
  {
    name: "Tools",
    category: "function",
    description: "Opens the tools menu on the console.",
    syntax: "Tools",
    examples: ["Tools"],
    docUrl: keywordDocUrl("tools"),
  },
  {
    name: "Top",
    category: "function",
    description: "Jumps to the top (first cue) of a sequence.",
    syntax: "Top [executor]",
    examples: ["Top Executor 1"],
    docUrl: keywordDocUrl("top"),
  },
  {
    name: "Unblock",
    category: "function",
    description: "Removes blocked values from cues, restoring attribute tracking.",
    syntax: "Unblock [object]",
    examples: ["Unblock Cue 3"],
    docUrl: keywordDocUrl("unblock"),
  },
  {
    name: "Unlock",
    category: "function",
    description: "Unlocks the console or a locked object.",
    syntax: "Unlock",
    examples: ["Unlock"],
    docUrl: keywordDocUrl("unlock"),
  },
  {
    name: "UpdateFirmware",
    category: "function",
    description: "Updates the console firmware to a newer version.",
    syntax: "UpdateFirmware",
    examples: ["UpdateFirmware"],
    docUrl: keywordDocUrl("updatefirmware"),
  },
  {
    name: "UpdateSoftware",
    category: "function",
    description: "Updates the console software to a newer version.",
    syntax: "UpdateSoftware",
    examples: ["UpdateSoftware"],
    docUrl: keywordDocUrl("updatesoftware"),
  },
  {
    name: "UpdateThumbnails",
    category: "function",
    description: "Updates fixture thumbnails displayed in layout and fixture views.",
    syntax: "UpdateThumbnails",
    examples: ["UpdateThumbnails"],
    docUrl: keywordDocUrl("updatethumbnails"),
  },
  {
    name: "Version",
    category: "function",
    description: "Displays the current software version of the console.",
    syntax: "Version",
    examples: ["Version"],
    docUrl: keywordDocUrl("version"),
  },
];

const objectKeywordDocs: KeywordDoc[] = [
  {
    name: "Cue",
    category: "object",
    description: "A stored lighting state within a sequence.",
    syntax: "[Function] Cue [number]",
    examples: [
      "Store Cue 1 \"Intro\"",
      "Goto Cue 5",
    ],
    docUrl: keywordDocUrl("cue"),
  },
  {
    name: "Sequence",
    category: "object",
    description: "An ordered list of cues for playback.",
    syntax: "[Function] Sequence [number]",
    examples: [
      "Store Sequence 1",
      "Assign Sequence 1 At Executor 1.1",
    ],
    docUrl: keywordDocUrl("sequence"),
  },
  {
    name: "Executor",
    category: "object",
    description: "A physical or virtual control assigned to a sequence.",
    syntax: "[Function] Executor [number]",
    examples: ["Off Executor 1.1"],
    docUrl: keywordDocUrl("executor"),
  },
  {
    name: "Group",
    category: "object",
    description: "A named collection of fixtures for quick selection.",
    syntax: "[Function] Group [number]",
    examples: [
      "Store Group 1 \"Band\"",
      "Select Group 1",
    ],
    docUrl: keywordDocUrl("group"),
  },
  {
    name: "Preset",
    category: "object",
    description: "Stored attribute values that can be referenced in cues.",
    syntax: "[Function] Preset [number]",
    examples: [
      "Store Preset 4.1 \"Blue\"",
      "At Preset 4.1",
    ],
    docUrl: keywordDocUrl("preset"),
  },
  {
    name: "Channel",
    category: "object",
    description: "A logical control channel for a fixture.",
    syntax: "[Function] Channel [number]",
    examples: ["Channel 1 Thru 10 At 75"],
    docUrl: keywordDocUrl("channel"),
  },
  {
    name: "Fixture",
    category: "object",
    description: "A physical lighting device in the patch.",
    syntax: "[Function] Fixture [number]",
    examples: ["Select Fixture 1 Thru 12"],
    docUrl: keywordDocUrl("fixture"),
  },
  {
    name: "Macro",
    category: "object",
    description: "A stored sequence of console commands for automation.",
    syntax: "[Function] Macro [number]",
    examples: [
      "Store Macro 5",
      "Call Macro 5",
    ],
    docUrl: keywordDocUrl("macro"),
  },
  {
    name: "Effect",
    category: "object",
    description: "A dynamic effect applied to fixture attributes.",
    syntax: "[Function] Effect [number]",
    examples: [
      "Store Effect 1",
      "Assign Effect 1 At Executor 2.1",
    ],
    docUrl: keywordDocUrl("effect"),
  },
  {
    name: "Page",
    category: "object",
    description: "A page of executors that can be switched.",
    syntax: "Page [number]",
    examples: [
      "Page 2",
      "Goto Page 3",
    ],
    docUrl: keywordDocUrl("page"),
  },
  {
    name: "Fader",
    category: "object",
    description: "A physical or virtual fader control.",
    syntax: "[Function] Fader [number]",
    examples: ["List Fader 1"],
    docUrl: keywordDocUrl("fader"),
  },
  {
    name: "View",
    category: "object",
    description: "A saved screen layout configuration.",
    syntax: "[Function] View [number]",
    examples: [
      "Store View 3",
      "View 3",
    ],
    docUrl: keywordDocUrl("view"),
  },
  {
    name: "Layout",
    category: "object",
    description: "A graphical fixture layout for visualization.",
    syntax: "[Function] Layout [number]",
    examples: [
      "Store Layout 1",
      "Edit Layout 1",
    ],
    docUrl: keywordDocUrl("layout"),
  },
  {
    name: "World",
    category: "object",
    description: "A filter limiting which fixtures are visible or selectable.",
    syntax: "[Function] World [number]",
    examples: [
      "Store World 1 \"FrontTruss\"",
      "Assign World 1 At Executor 3.1",
    ],
    docUrl: keywordDocUrl("world"),
  },
  {
    name: "Timecode",
    category: "object",
    description: "A timecode show for time-based cue triggering.",
    syntax: "[Function] Timecode [number]",
    examples: [
      "Store Timecode 1",
      "Edit Timecode 1",
    ],
    docUrl: keywordDocUrl("timecode"),
  },
  {
    name: "Timer",
    category: "object",
    description: "A countdown or stopwatch timer.",
    syntax: "[Function] Timer [number]",
    examples: [
      "Store Timer 1",
      "Edit Timer 1",
    ],
    docUrl: keywordDocUrl("timer"),
  },
  {
    name: "Agenda",
    category: "object",
    description: "A scheduled event list for automated show execution.",
    syntax: "[Function] Agenda [number]",
    examples: [
      "Store Agenda 1",
      "Edit Agenda 1",
    ],
    docUrl: keywordDocUrl("agenda"),
  },
  {
    name: "Appearance",
    category: "object",
    description: "A visual appearance preset for UI elements and objects.",
    syntax: "[Function] Appearance [number]",
    examples: ["Assign Appearance 3 At Macro 1"],
    docUrl: keywordDocUrl("appearance"),
  },
  {
    name: "Attribute",
    category: "object",
    description:
      "A controllable parameter of a fixture such as intensity, color, or position.",
    syntax: "[Function] Attribute [name]",
    examples: ["List Attribute \"Dimmer\""],
    docUrl: keywordDocUrl("attribute"),
  },
  {
    name: "AutoCreate",
    category: "object",
    description: "An automatic object creation setting for show programming.",
    syntax: "[Function] AutoCreate [name]",
    examples: ["List AutoCreate"],
    docUrl: keywordDocUrl("autocreate"),
  },
  {
    name: "ButtonPage",
    category: "object",
    description: "A page of button executors.",
    syntax: "[Function] ButtonPage [number]",
    examples: ["List ButtonPage 1"],
    docUrl: keywordDocUrl("buttonpage"),
  },
  {
    name: "Camera",
    category: "object",
    description: "A virtual camera for 3D stage visualization.",
    syntax: "[Function] Camera [number]",
    examples: [
      "Store Camera 1",
      "Edit Camera 1",
    ],
    docUrl: keywordDocUrl("camera"),
  },
  {
    name: "ChannelFader",
    category: "object",
    description: "A fader assigned to a specific channel for direct control.",
    syntax: "[Function] ChannelFader [number]",
    examples: ["List ChannelFader 1"],
    docUrl: keywordDocUrl("channelfader"),
  },
  {
    name: "ChannelPage",
    category: "object",
    description: "A page of channel faders.",
    syntax: "[Function] ChannelPage [number]",
    examples: ["List ChannelPage 1"],
    docUrl: keywordDocUrl("channelpage"),
  },
  {
    name: "Crossfade",
    category: "object",
    description: "A transition parameter controlling the crossfade between cues.",
    syntax: "Assign Crossfade [time] Cue [number]",
    examples: ["Assign Crossfade 3 Cue 1"],
    docUrl: keywordDocUrl("crossfade"),
  },
  {
    name: "CrossfadeA",
    category: "object",
    description:
      "The first crossfade path (A) for split crossfade transitions.",
    syntax: "Assign CrossfadeA [time] Cue [number]",
    examples: ["Assign CrossfadeA 2 Cue 1"],
    docUrl: keywordDocUrl("crossfadea"),
  },
  {
    name: "CrossfadeB",
    category: "object",
    description:
      "The second crossfade path (B) for split crossfade transitions.",
    syntax: "Assign CrossfadeB [time] Cue [number]",
    examples: ["Assign CrossfadeB 4 Cue 1"],
    docUrl: keywordDocUrl("crossfadeb"),
  },
  {
    name: "Dmx",
    category: "object",
    description: "A DMX output configuration object.",
    syntax: "[Function] Dmx [number]",
    examples: ["List Dmx 1"],
    docUrl: keywordDocUrl("dmx"),
  },
  {
    name: "DmxUniverse",
    category: "object",
    description: "A single DMX universe of 512 channels.",
    syntax: "[Function] DmxUniverse [number]",
    examples: ["List DmxUniverse 1"],
    docUrl: keywordDocUrl("dmxuniverse"),
  },
  {
    name: "EffectAttack",
    category: "object",
    description: "The attack time parameter of an effect.",
    syntax: "Assign EffectAttack [value] Effect [number]",
    examples: ["Assign EffectAttack 50 Effect 1"],
    docUrl: keywordDocUrl("effectattack"),
  },
  {
    name: "EffectBPM",
    category: "object",
    description: "The beats-per-minute tempo parameter of an effect.",
    syntax: "Assign EffectBPM [value] Effect [number]",
    examples: ["Assign EffectBPM 120 Effect 1"],
    docUrl: keywordDocUrl("effectbpm"),
  },
  {
    name: "EffectDecay",
    category: "object",
    description: "The decay time parameter of an effect.",
    syntax: "Assign EffectDecay [value] Effect [number]",
    examples: ["Assign EffectDecay 20 Effect 1"],
    docUrl: keywordDocUrl("effectdecay"),
  },
  {
    name: "EffectDelay",
    category: "object",
    description: "The delay time parameter of an effect.",
    syntax: "Assign EffectDelay [value] Effect [number]",
    examples: ["Assign EffectDelay 10 Effect 1"],
    docUrl: keywordDocUrl("effectdelay"),
  },
  {
    name: "EffectFade",
    category: "object",
    description: "The fade time parameter of an effect.",
    syntax: "Assign EffectFade [value] Effect [number]",
    examples: ["Assign EffectFade 2 Effect 1"],
    docUrl: keywordDocUrl("effectfade"),
  },
  {
    name: "EffectForm",
    category: "object",
    description: "The waveform shape parameter of an effect.",
    syntax: "Assign EffectForm [value] Effect [number]",
    examples: ["Assign EffectForm 3 Effect 1"],
    docUrl: keywordDocUrl("effectform"),
  },
  {
    name: "EffectHZ",
    category: "object",
    description: "The frequency parameter of an effect in Hertz.",
    syntax: "Assign EffectHZ [value] Effect [number]",
    examples: ["Assign EffectHZ 2 Effect 1"],
    docUrl: keywordDocUrl("effecthz"),
  },
  {
    name: "EffectHigh",
    category: "object",
    description: "The high value parameter of an effect.",
    syntax: "Assign EffectHigh [value] Effect [number]",
    examples: ["Assign EffectHigh 100 Effect 1"],
    docUrl: keywordDocUrl("effecthigh"),
  },
  {
    name: "EffectID",
    category: "object",
    description: "The ID parameter of an effect for fixture assignment.",
    syntax: "Assign EffectID [value] Effect [number]",
    examples: ["Assign EffectID 1 Effect 1"],
    docUrl: keywordDocUrl("effectid"),
  },
  {
    name: "EffectLow",
    category: "object",
    description: "The low value parameter of an effect.",
    syntax: "Assign EffectLow [value] Effect [number]",
    examples: ["Assign EffectLow 0 Effect 1"],
    docUrl: keywordDocUrl("effectlow"),
  },
  {
    name: "EffectPhase",
    category: "object",
    description: "The phase offset parameter of an effect.",
    syntax: "Assign EffectPhase [value] Effect [number]",
    examples: ["Assign EffectPhase 180 Effect 1"],
    docUrl: keywordDocUrl("effectphase"),
  },
  {
    name: "EffectSec",
    category: "object",
    description: "The speed parameter of an effect in seconds.",
    syntax: "Assign EffectSec [value] Effect [number]",
    examples: ["Assign EffectSec 1 Effect 1"],
    docUrl: keywordDocUrl("effectsec"),
  },
  {
    name: "EffectSpeedGroup",
    category: "object",
    description: "A speed group for synchronizing multiple effects.",
    syntax: "Assign EffectSpeedGroup [value] Effect [number]",
    examples: ["Assign EffectSpeedGroup 2 Effect 1"],
    docUrl: keywordDocUrl("effectspeedgroup"),
  },
  {
    name: "EffectWidth",
    category: "object",
    description: "The width parameter of an effect waveform.",
    syntax: "Assign EffectWidth [value] Effect [number]",
    examples: ["Assign EffectWidth 50 Effect 1"],
    docUrl: keywordDocUrl("effectwidth"),
  },
  {
    name: "ExecButton1",
    category: "object",
    description: "The first executor button assignment.",
    syntax: "Assign ExecButton1 [function] Executor [number]",
    examples: ["Assign ExecButton1 \"Flash\" Executor 1.1"],
    docUrl: keywordDocUrl("execbutton1"),
  },
  {
    name: "ExecButton2",
    category: "object",
    description: "The second executor button assignment.",
    syntax: "Assign ExecButton2 [function] Executor [number]",
    examples: ["Assign ExecButton2 \"Go\" Executor 1.1"],
    docUrl: keywordDocUrl("execbutton2"),
  },
  {
    name: "ExecButton3",
    category: "object",
    description: "The third executor button assignment.",
    syntax: "Assign ExecButton3 [function] Executor [number]",
    examples: ["Assign ExecButton3 \"Temp\" Executor 1.1"],
    docUrl: keywordDocUrl("execbutton3"),
  },
  {
    name: "FadePath",
    category: "object",
    description: "The fade path curve used for transitions.",
    syntax: "Assign FadePath [number] Cue [number]",
    examples: ["Assign FadePath 2 Cue 1"],
    docUrl: keywordDocUrl("fadepath"),
  },
  {
    name: "FaderPage",
    category: "object",
    description: "A page of fader executors.",
    syntax: "[Function] FaderPage [number]",
    examples: ["List FaderPage 1"],
    docUrl: keywordDocUrl("faderpage"),
  },
  {
    name: "Feature",
    category: "object",
    description:
      "A feature group of fixture attributes such as dimmer, color, or position.",
    syntax: "[Function] Feature [name]",
    examples: ["List Feature \"Color\""],
    docUrl: keywordDocUrl("feature"),
  },
  {
    name: "Filter",
    category: "object",
    description: "A filter for limiting displayed or accessible objects.",
    syntax: "[Function] Filter [number]",
    examples: [
      "Store Filter 1 \"NoBeam\"",
      "Assign Filter 1 At Sequence 1",
    ],
    docUrl: keywordDocUrl("filter"),
  },
  {
    name: "FixtureType",
    category: "object",
    description:
      "A fixture type definition describing a lighting device's capabilities.",
    syntax: "[Function] FixtureType [name]",
    examples: ["List FixtureType \"MAC Aura\""],
    docUrl: keywordDocUrl("fixturetype"),
  },
  {
    name: "Form",
    category: "object",
    description: "A waveform shape used in effects.",
    syntax: "Assign Form [number] Effect [number]",
    examples: ["Assign Form 3 Effect 1"],
    docUrl: keywordDocUrl("form"),
  },
  {
    name: "Gel",
    category: "object",
    description: "A color gel reference from a gel library.",
    syntax: "[Function] Gel [number]",
    examples: ["List Gel 201"],
    docUrl: keywordDocUrl("gel"),
  },
  {
    name: "Image",
    category: "object",
    description: "An image resource used in layouts or screens.",
    syntax: "[Function] Image [number]",
    examples: [
      "Import Image \"logo.png\"",
      "List Image 1",
    ],
    docUrl: keywordDocUrl("image"),
  },
  {
    name: "Item3D",
    category: "object",
    description: "A 3D object used in the stage visualization.",
    syntax: "[Function] Item3D [number]",
    examples: ["Move3D Item3D 1"],
    docUrl: keywordDocUrl("item3d"),
  },
  {
    name: "Lua",
    category: "object",
    description: "A Lua scripting plugin for custom console functionality.",
    syntax: "[Function] Lua [name]",
    examples: ["List Lua"],
    docUrl: keywordDocUrl("lua"),
  },
  {
    name: "MAtricks",
    category: "object",
    description:
      "A matrix-based selection and manipulation tool for fixture groups.",
    syntax: "[Function] MAtricks [number]",
    examples: [
      "Store MAtricks 1",
      "Assign MAtricks 1 At Executor 1.1",
    ],
    docUrl: keywordDocUrl("matricks"),
  },
  {
    name: "Mask",
    category: "object",
    description: "A selection mask for filtering fixture attributes.",
    syntax: "[Function] Mask [number]",
    examples: [
      "Store Mask 1",
      "Assign Mask 1 At Sequence 1",
    ],
    docUrl: keywordDocUrl("mask"),
  },
  {
    name: "Master",
    category: "object",
    description:
      "A master fader for controlling groups of executors or parameters.",
    syntax: "[Function] Master [number]",
    examples: ["Assign Master 3 At Executor 4.1"],
    docUrl: keywordDocUrl("master"),
  },
  {
    name: "MediaServer",
    category: "object",
    description: "A media server configuration for video content control.",
    syntax: "[Function] MediaServer [number]",
    examples: ["List MediaServer 1"],
    docUrl: keywordDocUrl("mediaserver"),
  },
  {
    name: "Message",
    category: "object",
    description: "A system message or user-defined message.",
    syntax: "[Function] Message [number]",
    examples: ["List Message"],
    docUrl: keywordDocUrl("message"),
  },
  {
    name: "Messages",
    category: "object",
    description: "The message center containing system and user messages.",
    syntax: "[Function] Messages",
    examples: ["List Messages"],
    docUrl: keywordDocUrl("messages"),
  },
  {
    name: "Model",
    category: "object",
    description: "A 3D model used for fixture visualization.",
    syntax: "[Function] Model [name]",
    examples: ["List Model"],
    docUrl: keywordDocUrl("model"),
  },
  {
    name: "Normal",
    category: "object",
    description: "The normal playback mode for executors.",
    syntax: "Assign Normal Executor [number]",
    examples: ["Assign Normal Executor 1.1"],
    docUrl: keywordDocUrl("normal"),
  },
  {
    name: "PMArea",
    category: "object",
    description: "A partial show merge area for selective data import.",
    syntax: "[Function] PMArea [number]",
    examples: ["List PMArea 1"],
    docUrl: keywordDocUrl("pmarea"),
  },
  {
    name: "Part",
    category: "object",
    description: "A cue part for splitting cue data into timed sections.",
    syntax: "[Function] Part [number] Cue [number]",
    examples: ["Store Part 2 Cue 1"],
    docUrl: keywordDocUrl("part"),
  },
  {
    name: "Plugin",
    category: "object",
    description: "A Lua-based plugin extending console functionality.",
    syntax: "[Function] Plugin [number]",
    examples: [
      "Store Plugin 1",
      "Call Plugin 1",
    ],
    docUrl: keywordDocUrl("plugin"),
  },
  {
    name: "PresetType",
    category: "object",
    description: "A preset type category such as dimmer, color, or position.",
    syntax: "[Function] PresetType [number]",
    examples: ["List PresetType 4"],
    docUrl: keywordDocUrl("presettype"),
  },
  {
    name: "PreviewExecutor",
    category: "object",
    description: "An executor used in preview or blind mode.",
    syntax: "[Function] PreviewExecutor [number]",
    examples: ["Preview PreviewExecutor 1.1"],
    docUrl: keywordDocUrl("previewexecutor"),
  },
  {
    name: "Profile",
    category: "object",
    description:
      "A user profile containing personal settings and permissions.",
    syntax: "[Function] Profile [name]",
    examples: ["List Profile"],
    docUrl: keywordDocUrl("profile"),
  },
  {
    name: "Protocol",
    category: "object",
    description: "A network protocol configuration for data output.",
    syntax: "[Function] Protocol [name]",
    examples: ["List Protocol"],
    docUrl: keywordDocUrl("protocol"),
  },
  {
    name: "Rate",
    category: "object",
    description: "A rate modifier for adjusting effect or executor speed.",
    syntax: "Assign Rate [value] Executor [number]",
    examples: ["Assign Rate 0.75 Executor 1.1"],
    docUrl: keywordDocUrl("rate"),
  },
  {
    name: "RdmAutomatch",
    category: "object",
    description: "RDM automatic matching of discovered devices.",
    syntax: "[Function] RdmAutomatch",
    examples: ["List RdmAutomatch"],
    docUrl: keywordDocUrl("rdmautomatch"),
  },
  {
    name: "RdmAutopatch",
    category: "object",
    description: "RDM automatic patching of discovered devices.",
    syntax: "[Function] RdmAutopatch",
    examples: ["List RdmAutopatch"],
    docUrl: keywordDocUrl("rdmautopatch"),
  },
  {
    name: "RdmFixtureType",
    category: "object",
    description: "An RDM-discovered fixture type definition.",
    syntax: "[Function] RdmFixtureType [name]",
    examples: ["List RdmFixtureType"],
    docUrl: keywordDocUrl("rdmfixturetype"),
  },
  {
    name: "RdmInfo",
    category: "object",
    description: "RDM device information and parameters.",
    syntax: "[Function] RdmInfo",
    examples: ["List RdmInfo"],
    docUrl: keywordDocUrl("rdminfo"),
  },
  {
    name: "RdmList",
    category: "object",
    description: "A list of discovered RDM devices.",
    syntax: "[Function] RdmList",
    examples: ["List RdmList"],
    docUrl: keywordDocUrl("rdmlist"),
  },
  {
    name: "RdmSetParameter",
    category: "object",
    description:
      "An RDM parameter setting for remote device configuration.",
    syntax: "[Function] RdmSetParameter [name]",
    examples: ["List RdmSetParameter"],
    docUrl: keywordDocUrl("rdmsetparameter"),
  },
  {
    name: "RdmSetpatch",
    category: "object",
    description: "An RDM patch setting for remote device addressing.",
    syntax: "[Function] RdmSetpatch [value]",
    examples: ["List RdmSetpatch"],
    docUrl: keywordDocUrl("rdmsetpatch"),
  },
  {
    name: "RdmUnmatch",
    category: "object",
    description: "RDM unmatching of previously matched devices.",
    syntax: "[Function] RdmUnmatch",
    examples: ["List RdmUnmatch"],
    docUrl: keywordDocUrl("rdmunmatch"),
  },
  {
    name: "Remote",
    category: "object",
    description: "A remote console configuration for network control.",
    syntax: "[Function] Remote [name]",
    examples: ["List Remote"],
    docUrl: keywordDocUrl("remote"),
  },
  {
    name: "Root",
    category: "object",
    description: "The root object of the console's object hierarchy.",
    syntax: "[Function] Root",
    examples: ["List Root"],
    docUrl: keywordDocUrl("root"),
  },
  {
    name: "Screen",
    category: "object",
    description: "A display screen configuration on the console.",
    syntax: "[Function] Screen [number]",
    examples: [
      "Store Screen 2",
      "Edit Screen 2",
    ],
    docUrl: keywordDocUrl("screen"),
  },
  {
    name: "SearchResult",
    category: "object",
    description: "A result from a search operation within the show data.",
    syntax: "[Function] SearchResult [number]",
    examples: [
      "Search \"Spot\"",
      "List SearchResult",
    ],
    docUrl: keywordDocUrl("searchresult"),
  },
  {
    name: "Selection",
    category: "object",
    description: "The current fixture selection state.",
    syntax: "[Function] Selection",
    examples: [
      "Store Selection 1",
      "List Selection",
    ],
    docUrl: keywordDocUrl("selection"),
  },
  {
    name: "SetHostname",
    category: "object",
    description:
      "A hostname configuration object for network identification.",
    syntax: "[Function] SetHostname [name]",
    examples: ["Set SetHostname \"FOH-MA2\""],
    docUrl: keywordDocUrl("sethostname"),
  },
  {
    name: "SetNetworkSpeed",
    category: "object",
    description: "A network speed configuration object.",
    syntax: "[Function] SetNetworkSpeed [value]",
    examples: ["Set SetNetworkSpeed 1000"],
    docUrl: keywordDocUrl("setnetworkspeed"),
  },
  {
    name: "SpecialMaster",
    category: "object",
    description:
      "A special master fader for global parameters like grand master or sound.",
    syntax: "[Function] SpecialMaster [number]",
    examples: ["Assign SpecialMaster 2 At Executor 5.1"],
    docUrl: keywordDocUrl("specialmaster"),
  },
  {
    name: "Surface",
    category: "object",
    description: "A virtual screen surface for multi-display setups.",
    syntax: "[Function] Surface [number]",
    examples: ["List Surface 1"],
    docUrl: keywordDocUrl("surface"),
  },
  {
    name: "Telnet",
    category: "object",
    description: "A telnet connection interface for remote command input.",
    syntax: "[Function] Telnet [name]",
    examples: ["List Telnet"],
    docUrl: keywordDocUrl("telnet"),
  },
  {
    name: "TimecodeSlot",
    category: "object",
    description: "A timecode slot for time-based show control.",
    syntax: "[Function] TimecodeSlot [number]",
    examples: ["Store TimecodeSlot 1 Timecode 1"],
    docUrl: keywordDocUrl("timecodeslot"),
  },
  {
    name: "User",
    category: "object",
    description: "A console user account with associated permissions.",
    syntax: "[Function] User [name]",
    examples: [
      "Login \"Admin\" \"admin\"",
      "List User",
    ],
    docUrl: keywordDocUrl("user"),
  },
  {
    name: "UserProfile",
    category: "object",
    description:
      "A user profile defining personal preferences and access rights.",
    syntax: "[Function] UserProfile [name]",
    examples: ["List UserProfile"],
    docUrl: keywordDocUrl("userprofile"),
  },
  {
    name: "Value",
    category: "object",
    description: "A stored value object for attribute data.",
    syntax: "[Function] Value [number]",
    examples: ["List Value 1"],
    docUrl: keywordDocUrl("value"),
  },
  {
    name: "ViewButton",
    category: "object",
    description: "A button assigned to recall a specific view layout.",
    syntax: "[Function] ViewButton [number]",
    examples: ["Assign View 3 At ViewButton 1"],
    docUrl: keywordDocUrl("viewbutton"),
  },
  {
    name: "ViewPage",
    category: "object",
    description: "A page of view buttons.",
    syntax: "[Function] ViewPage [number]",
    examples: ["List ViewPage 1"],
    docUrl: keywordDocUrl("viewpage"),
  },
];

const helpingKeywordDocs: KeywordDoc[] = [
  {
    name: "At",
    category: "helping",
    description: "Sets attribute values between fixture selection and value.",
    syntax: "[fixture-selection] At [value]",
    examples: ["Fixture 1 At 50"],
    docUrl: keywordDocUrl("at"),
  },
  {
    name: "Thru",
    category: "helping",
    description: "Creates a range between two values.",
    syntax: "[start] Thru [end]",
    examples: ["Fixture 1 Thru 10"],
    docUrl: keywordDocUrl("thru"),
  },
  {
    name: "And",
    category: "helping",
    description: "Adds to a selection or combines conditions with logical AND.",
    syntax: "[term] And [term]",
    examples: ["Fixture 1 And 3"],
    docUrl: keywordDocUrl("and"),
  },
  {
    name: "Or",
    category: "helping",
    description: "Combines conditions with logical OR.",
    syntax: "[condition] Or [condition]",
    examples: ["If $a = 1 Or $b = 2"],
    docUrl: keywordDocUrl("or"),
  },
  {
    name: "Please",
    category: "helping",
    description: "Confirms and executes the current command.",
    syntax: "[command] Please",
    examples: ["Delete Group 4 Please"],
    docUrl: keywordDocUrl("please"),
  },
  {
    name: "Full",
    category: "helping",
    description: "Sets dimmer to 100 percent.",
    syntax: "[fixture-selection] At Full",
    examples: ["Fixture 1 At Full"],
    docUrl: keywordDocUrl("full"),
  },
  {
    name: "Zero",
    category: "helping",
    description: "Sets dimmer to 0 percent.",
    syntax: "[fixture-selection] At Zero",
    examples: ["Fixture 1 At Zero"],
    docUrl: keywordDocUrl("zero"),
  },
  {
    name: "With",
    category: "helping",
    description: "Specifies additional parameters in a command.",
    syntax: "[command] With [parameter]",
    examples: ["Store Cue 1 With Preset 4.1"],
    docUrl: keywordDocUrl("with"),
  },
  {
    name: "EndIf",
    category: "helping",
    description: "Ends a conditional block in macros.",
    syntax: "EndIf",
    examples: ["EndIf"],
    docUrl: keywordDocUrl("endif"),
  },
  {
    name: "Default",
    category: "helping",
    description: "Resets attributes to default values.",
    syntax: "Default [object]",
    examples: ["Default Fixture 1"],
    docUrl: keywordDocUrl("default"),
  },
  {
    name: "Alert",
    category: "helping",
    description:
      "Triggers an alert message on consoles and stations in the session.",
    syntax: "Alert [message]",
    examples: ['Alert "Show starts in 5 minutes"'],
    docUrl: keywordDocUrl("alert"),
  },
  {
    name: "AllButtonExecutors",
    category: "helping",
    description: "Targets all button-type executors for a command.",
    syntax: "[command] AllButtonExecutors",
    examples: ["Off AllButtonExecutors"],
    docUrl: keywordDocUrl("allbuttonexecutors"),
  },
  {
    name: "AllChaseExecutors",
    category: "helping",
    description: "Targets all chase-type executors for a command.",
    syntax: "[command] AllChaseExecutors",
    examples: ["Off AllChaseExecutors"],
    docUrl: keywordDocUrl("allchaseexecutors"),
  },
  {
    name: "AllFaderExecutors",
    category: "helping",
    description: "Targets all fader-type executors for a command.",
    syntax: "[command] AllFaderExecutors",
    examples: ["Off AllFaderExecutors"],
    docUrl: keywordDocUrl("allfaderexecutors"),
  },
  {
    name: "AllSequExecutors",
    category: "helping",
    description: "Targets all sequence executors for a command.",
    syntax: "[command] AllSequExecutors",
    examples: ["Off AllSequExecutors"],
    docUrl: keywordDocUrl("allsequexecutors"),
  },
  {
    name: "CmdDelay",
    category: "helping",
    description:
      "Sets a command delay time before the next command line executes in a macro.",
    syntax: "CmdDelay [time]",
    examples: ["CmdDelay 2", "Go Executor 1 CmdDelay 5"],
    docUrl: keywordDocUrl("cmddelay"),
  },
  {
    name: "DefGoBack",
    category: "helping",
    description:
      "Defines the default GoBack timing for a cue or sequence.",
    syntax: "Assign DefGoBack [time] Cue [cue-number]",
    examples: ["Assign DefGoBack 3 Cue 1"],
    docUrl: keywordDocUrl("defgoback"),
  },
  {
    name: "DefGoForward",
    category: "helping",
    description:
      "Defines the default GoForward timing for a cue or sequence.",
    syntax: "Assign DefGoForward [time] Cue [cue-number]",
    examples: ["Assign DefGoForward 2 Cue 1"],
    docUrl: keywordDocUrl("defgoforward"),
  },
  {
    name: "DefGoPause",
    category: "helping",
    description:
      "Defines the default GoPause timing for a cue or sequence.",
    syntax: "Assign DefGoPause [time] Cue [cue-number]",
    examples: ["Assign DefGoPause 1 Cue 1"],
    docUrl: keywordDocUrl("defgopause"),
  },
  {
    name: "Delay",
    category: "helping",
    description:
      "Sets the delay time before an attribute change begins during a cue transition.",
    syntax: "[command] Delay [time]",
    examples: [
      "Store Cue 1 Delay 2",
      "Fixture 1 Thru 10 At 50 Delay 0 Thru 5",
    ],
    docUrl: keywordDocUrl("delay"),
  },
  {
    name: "Down",
    category: "helping",
    description:
      "Decreases the attribute value by one step or moves down in a selection.",
    syntax: "[object] Down",
    examples: ["Channel 1 At Down", "Executor 1 Down"],
    docUrl: keywordDocUrl("down"),
  },
  {
    name: "Empty",
    category: "helping",
    description:
      "Represents an empty or cleared value, used to remove stored data.",
    syntax: "[command] Empty",
    examples: ["Store Cue 1 Empty"],
    docUrl: keywordDocUrl("empty"),
  },
  {
    name: "Escape",
    category: "helping",
    description:
      "Cancels the current operation or closes the active dialog.",
    syntax: "Escape",
    examples: ["Escape"],
    docUrl: keywordDocUrl("escape"),
  },
  {
    name: "Fade",
    category: "helping",
    description:
      "Sets the fade time for attribute transitions during cue playback.",
    syntax: "[command] Fade [time]",
    examples: ["Store Cue 1 Fade 5", "Goto Cue 2 Fade 3"],
    docUrl: keywordDocUrl("fade"),
  },
  {
    name: "FullHighlight",
    category: "helping",
    description:
      "Activates full highlight mode, setting all attributes to their highlight values.",
    syntax: "FullHighlight",
    examples: ["FullHighlight", "Select Fixture 1 FullHighlight"],
    docUrl: keywordDocUrl("fullhighlight"),
  },
  {
    name: "IdentifyFaderModule",
    category: "helping",
    description:
      "Identifies a physical fader module on the console by flashing its indicators.",
    syntax: "IdentifyFaderModule [module-number]",
    examples: ["IdentifyFaderModule 1"],
    docUrl: keywordDocUrl("identifyfadermodule"),
  },
  {
    name: "Interleave",
    category: "helping",
    description:
      "Distributes the current selection into interleaved groups for MAtricks operations.",
    syntax: "Interleave [value]",
    examples: ["Interleave 2", "MAtricks Interleave 3"],
    docUrl: keywordDocUrl("interleave"),
  },
  {
    name: "Next",
    category: "helping",
    description:
      "Advances to the next item in a selection, fixture sheet, or sequence.",
    syntax: "Next",
    examples: ["Next", "Next Fixture"],
    docUrl: keywordDocUrl("next"),
  },
  {
    name: "OutDelay",
    category: "helping",
    description:
      "Sets the delay time for outgoing (release) attribute transitions in a cue.",
    syntax: "[command] OutDelay [time]",
    examples: ["Store Cue 1 OutDelay 2"],
    docUrl: keywordDocUrl("outdelay"),
  },
  {
    name: "OutFade",
    category: "helping",
    description:
      "Sets the fade time for outgoing (release) attribute transitions in a cue.",
    syntax: "[command] OutFade [time]",
    examples: ["Store Cue 1 OutFade 3", "Goto Cue 2 OutFade 5"],
    docUrl: keywordDocUrl("outfade"),
  },
  {
    name: "Previous",
    category: "helping",
    description:
      "Goes back to the previous item in a selection, fixture sheet, or sequence.",
    syntax: "Previous",
    examples: ["Previous", "Previous Fixture"],
    docUrl: keywordDocUrl("previous"),
  },
  {
    name: "SnapPercent",
    category: "helping",
    description:
      "Sets the snap percentage point within a crossfade where snap attributes change.",
    syntax: "[command] SnapPercent [value]",
    examples: ["Store Cue 1 SnapPercent 50", "Assign SnapPercent 0 Cue 3"],
    docUrl: keywordDocUrl("snappercent"),
  },
  {
    name: "ToFull",
    category: "helping",
    description:
      "Transitions the selected fixtures to full (100%) intensity.",
    syntax: "[fixture-selection] ToFull",
    examples: ["Fixture 1 Thru 10 ToFull"],
    docUrl: keywordDocUrl("tofull"),
  },
  {
    name: "ToZero",
    category: "helping",
    description:
      "Transitions the selected fixtures to zero (0%) intensity.",
    syntax: "[fixture-selection] ToZero",
    examples: ["Fixture 1 Thru 10 ToZero"],
    docUrl: keywordDocUrl("tozero"),
  },
  {
    name: "Toggle",
    category: "helping",
    description:
      "Toggles an executor or function between its on and off states.",
    syntax: "Toggle [object]",
    examples: ["Toggle Executor 1", "Assign Toggle Executor 2.1"],
    docUrl: keywordDocUrl("toggle"),
  },
   {
     name: "Up",
     category: "helping",
     description:
       "Increases the attribute value by one step or moves up in a selection.",
     syntax: "[object] Up",
     examples: ["Channel 1 At Up", "Executor 1 Up"],
     docUrl: keywordDocUrl("up"),
   },
   {
     name: "WebRemoteProgOnly",
     category: "helping",
     description: "Restricts web remote access to programmer-only mode, limiting remote control capabilities.",
     syntax: "WebRemoteProgOnly",
     examples: ["WebRemoteProgOnly"],
     docUrl: keywordDocUrl("webremoteprogonly"),
   },
];

export const keywordDocs = new Map<string, KeywordDoc>(
  [...functionKeywordDocs, ...objectKeywordDocs, ...helpingKeywordDocs].map((doc) => [
    doc.name.toLowerCase(),
    doc,
  ]),
);

export function getKeywordDoc(word: string): KeywordDoc | undefined {
  return keywordDocs.get(word.toLowerCase());
}
