export interface KeywordDoc {
  name: string;
  category: "function" | "object" | "helping";
  description: string;
  syntax?: string;
  examples?: string[];
  docUrl?: string;
}

function keywordDocUrl(name: string): string {
  return `https://help.malighting.com/grandMA2/en/help/key_keyword_${name.toLowerCase()}.html`;
}

const functionKeywordDocs: KeywordDoc[] = [
  {
    name: "Store",
    category: "function",
    description:
      "Saves programmer content into the show file; by default stores a cue.",
    syntax: 'Store [object-list] "Name" /[option]',
    examples: ['Store Cue 1 "Opening Look"'],
    docUrl: keywordDocUrl("store"),
  },
  {
    name: "Copy",
    category: "function",
    description: "Creates a duplicate of objects.",
    syntax: "Copy [object] At [target]",
    examples: ["Copy Cue 1 At Cue 5"],
    docUrl: keywordDocUrl("copy"),
  },
  {
    name: "Delete",
    category: "function",
    description: "Removes data from the show file.",
    syntax: "Delete [object-list]",
    examples: ["Delete Cue 7"],
    docUrl: keywordDocUrl("delete"),
  },
  {
    name: "Go",
    category: "function",
    description: "Starts the next cue in a sequence (Go+).",
    syntax: "Go [executor]",
    examples: ["Go"],
    docUrl: keywordDocUrl("go"),
  },
  {
    name: "Goto",
    category: "function",
    description: "Jumps directly to a specific cue.",
    syntax: "Goto Cue [number]",
    examples: ["Goto Cue 5"],
    docUrl: keywordDocUrl("goto"),
  },
  {
    name: "Move",
    category: "function",
    description: "Moves objects to a new location.",
    syntax: "Move [object] At [target]",
    examples: ["Move Cue 1 At Cue 10"],
    docUrl: keywordDocUrl("move"),
  },
  {
    name: "Assign",
    category: "function",
    description: "Assigns an object to an executor or button.",
    syntax: "Assign [object] At [executor]",
    examples: ["Assign Sequence 1 At Executor 1"],
    docUrl: keywordDocUrl("assign"),
  },
  {
    name: "Update",
    category: "function",
    description: "Updates stored data with current programmer content.",
    syntax: "Update [object]",
    examples: ["Update Cue 3"],
    docUrl: keywordDocUrl("update"),
  },
  {
    name: "Clear",
    category: "function",
    description: "Clears the programmer or active values.",
    syntax: "Clear",
    examples: ["Clear"],
    docUrl: keywordDocUrl("clear"),
  },
  {
    name: "ClearAll",
    category: "function",
    description: "Clears all programmer content including selection.",
    syntax: "ClearAll",
    examples: ["ClearAll"],
    docUrl: keywordDocUrl("clearall"),
  },
  {
    name: "Select",
    category: "function",
    description: "Selects fixtures or channels for editing.",
    syntax: "Select [object]",
    examples: ["Select Fixture 1 Thru 10"],
    docUrl: keywordDocUrl("select"),
  },
  {
    name: "Off",
    category: "function",
    description: "Turns off an executor or releases a cue.",
    syntax: "Off [executor]",
    examples: ["Off Executor 1"],
    docUrl: keywordDocUrl("off"),
  },
  {
    name: "On",
    category: "function",
    description: "Turns on an executor.",
    syntax: "On [executor]",
    examples: ["On Executor 2"],
    docUrl: keywordDocUrl("on"),
  },
  {
    name: "Edit",
    category: "function",
    description: "Opens an object for editing.",
    syntax: "Edit [object]",
    examples: ["Edit Macro 1"],
    docUrl: keywordDocUrl("edit"),
  },
  {
    name: "Label",
    category: "function",
    description: "Assigns a name or label to an object.",
    syntax: 'Label [object] "name"',
    examples: ['Label Cue 1 "Opening Look"'],
    docUrl: keywordDocUrl("label"),
  },
  {
    name: "Park",
    category: "function",
    description: "Parks fixture output at the current value.",
    syntax: "Park [fixture]",
    examples: ["Park Fixture 3"],
    docUrl: keywordDocUrl("park"),
  },
  {
    name: "Unpark",
    category: "function",
    description: "Releases parked fixtures.",
    syntax: "Unpark [fixture]",
    examples: ["Unpark Fixture 3"],
    docUrl: keywordDocUrl("unpark"),
  },
  {
    name: "Record",
    category: "function",
    description: "Records a macro step.",
    syntax: "Record Macro [number]",
    examples: ["Record Macro 1"],
    docUrl: keywordDocUrl("record"),
  },
  {
    name: "Clone",
    category: "function",
    description: "Clones fixture data from one fixture to another.",
    syntax: "Clone Fixture [source] At Fixture [target]",
    examples: ["Clone Fixture 1 At Fixture 11"],
    docUrl: keywordDocUrl("clone"),
  },
  {
    name: "Import",
    category: "function",
    description: "Imports data from a file.",
    syntax: 'Import [type] "filename"',
    examples: ['Import Library "my_groups"'],
    docUrl: keywordDocUrl("import"),
  },
  {
    name: "Export",
    category: "function",
    description: "Exports data to a file.",
    syntax: 'Export [type] "filename"',
    examples: ['Export Group "my_groups"'],
    docUrl: keywordDocUrl("export"),
  },
  {
    name: "List",
    category: "function",
    description: "Displays a list view of objects.",
    syntax: "List [object-type]",
    examples: ["List Cue"],
    docUrl: keywordDocUrl("list"),
  },
  {
    name: "Load",
    category: "function",
    description: "Loads a cue into the programmer.",
    syntax: "Load Cue [number]",
    examples: ["Load Cue 1"],
    docUrl: keywordDocUrl("load"),
  },
  {
    name: "If",
    category: "function",
    description: "Conditional execution in macros.",
    syntax: "If [condition]",
    examples: ["If $myVar = 1"],
    docUrl: keywordDocUrl("if"),
  },
  {
    name: "Oops",
    category: "function",
    description: "Undoes the last action.",
    syntax: "Oops",
    examples: ["Oops"],
    docUrl: keywordDocUrl("oops"),
  },
  {
    name: "Blind",
    category: "function",
    description: "Enters blind mode for editing without output.",
    syntax: "Blind",
    examples: ["Blind"],
    docUrl: keywordDocUrl("blind"),
  },
  {
    name: "Flash",
    category: "function",
    description: "Momentarily sets an executor to full.",
    syntax: "Flash [executor]",
    examples: ["Flash Executor 1"],
    docUrl: keywordDocUrl("flash"),
  },
  {
    name: "Freeze",
    category: "function",
    description: "Freezes the current output of fixtures.",
    syntax: "Freeze [fixture]",
    examples: ["Freeze Fixture 1"],
    docUrl: keywordDocUrl("freeze"),
  },
];

const objectKeywordDocs: KeywordDoc[] = [
  {
    name: "Cue",
    category: "object",
    description: "A stored lighting state within a sequence.",
    docUrl: keywordDocUrl("cue"),
  },
  {
    name: "Sequence",
    category: "object",
    description: "An ordered list of cues for playback.",
    docUrl: keywordDocUrl("sequence"),
  },
  {
    name: "Executor",
    category: "object",
    description: "A physical or virtual control assigned to a sequence.",
    docUrl: keywordDocUrl("executor"),
  },
  {
    name: "Group",
    category: "object",
    description: "A named collection of fixtures for quick selection.",
    docUrl: keywordDocUrl("group"),
  },
  {
    name: "Preset",
    category: "object",
    description: "Stored attribute values that can be referenced in cues.",
    docUrl: keywordDocUrl("preset"),
  },
  {
    name: "Channel",
    category: "object",
    description: "A logical control channel for a fixture.",
    docUrl: keywordDocUrl("channel"),
  },
  {
    name: "Fixture",
    category: "object",
    description: "A physical lighting device in the patch.",
    docUrl: keywordDocUrl("fixture"),
  },
  {
    name: "Macro",
    category: "object",
    description: "A stored sequence of console commands for automation.",
    docUrl: keywordDocUrl("macro"),
  },
  {
    name: "Effect",
    category: "object",
    description: "A dynamic effect applied to fixture attributes.",
    docUrl: keywordDocUrl("effect"),
  },
  {
    name: "Page",
    category: "object",
    description: "A page of executors that can be switched.",
    docUrl: keywordDocUrl("page"),
  },
  {
    name: "Fader",
    category: "object",
    description: "A physical or virtual fader control.",
    docUrl: keywordDocUrl("fader"),
  },
  {
    name: "View",
    category: "object",
    description: "A saved screen layout configuration.",
    docUrl: keywordDocUrl("view"),
  },
  {
    name: "Layout",
    category: "object",
    description: "A graphical fixture layout for visualization.",
    docUrl: keywordDocUrl("layout"),
  },
  {
    name: "World",
    category: "object",
    description: "A filter limiting which fixtures are visible or selectable.",
    docUrl: keywordDocUrl("world"),
  },
  {
    name: "Timecode",
    category: "object",
    description: "A timecode show for time-based cue triggering.",
    docUrl: keywordDocUrl("timecode"),
  },
  {
    name: "Timer",
    category: "object",
    description: "A countdown or stopwatch timer.",
    docUrl: keywordDocUrl("timer"),
  },
];

const helpingKeywordDocs: KeywordDoc[] = [
  {
    name: "At",
    category: "helping",
    description: "Sets attribute values between fixture selection and value.",
    syntax: "[fixture-selection] At [value]",
    examples: ["Fixture 1 At 50"],
    docUrl: keywordDocUrl("at"),
  },
  {
    name: "Thru",
    category: "helping",
    description: "Creates a range between two values.",
    syntax: "[start] Thru [end]",
    examples: ["Fixture 1 Thru 10"],
    docUrl: keywordDocUrl("thru"),
  },
  {
    name: "And",
    category: "helping",
    description: "Adds to a selection or combines conditions with logical AND.",
    syntax: "[term] And [term]",
    examples: ["Fixture 1 And 3"],
    docUrl: keywordDocUrl("and"),
  },
  {
    name: "Or",
    category: "helping",
    description: "Combines conditions with logical OR.",
    syntax: "[condition] Or [condition]",
    examples: ["If $a = 1 Or $b = 2"],
    docUrl: keywordDocUrl("or"),
  },
  {
    name: "Please",
    category: "helping",
    description: "Confirms and executes the current command.",
    syntax: "[command] Please",
    examples: ["Delete Group 4 Please"],
    docUrl: keywordDocUrl("please"),
  },
  {
    name: "Full",
    category: "helping",
    description: "Sets dimmer to 100 percent.",
    syntax: "[fixture-selection] At Full",
    examples: ["Fixture 1 At Full"],
    docUrl: keywordDocUrl("full"),
  },
  {
    name: "Zero",
    category: "helping",
    description: "Sets dimmer to 0 percent.",
    syntax: "[fixture-selection] At Zero",
    examples: ["Fixture 1 At Zero"],
    docUrl: keywordDocUrl("zero"),
  },
  {
    name: "With",
    category: "helping",
    description: "Specifies additional parameters in a command.",
    syntax: "[command] With [parameter]",
    examples: ["Store Cue 1 With Preset 4.1"],
    docUrl: keywordDocUrl("with"),
  },
  {
    name: "EndIf",
    category: "helping",
    description: "Ends a conditional block in macros.",
    syntax: "EndIf",
    examples: ["EndIf"],
    docUrl: keywordDocUrl("endif"),
  },
  {
    name: "Default",
    category: "helping",
    description: "Resets attributes to default values.",
    syntax: "Default [object]",
    examples: ["Default Fixture 1"],
    docUrl: keywordDocUrl("default"),
  },
];

export const keywordDocs = new Map<string, KeywordDoc>(
  [...functionKeywordDocs, ...objectKeywordDocs, ...helpingKeywordDocs].map((doc) => [
    doc.name.toLowerCase(),
    doc,
  ]),
);

export function getKeywordDoc(word: string): KeywordDoc | undefined {
  return keywordDocs.get(word.toLowerCase());
}
